apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.serviceB.name }}
spec:
  host: {{ .Values.serviceB.name }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL