apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.serviceB.name }}
spec:
  hosts:
  - {{ .Values.serviceB.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.serviceB.name }}