apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
  - name: cuda-container
    image: nvidia/cuda:11.0-base
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
        nvidia.com/mig-1g.5gb: "1"
