apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-amd64
spec:
  selector:
    matchLabels:
      app: nginx-amd64
  template:
    metadata:
      labels:
        app: nginx-amd64
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
