
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
data:
  fernet-key: <base64 encoded fernet key> # replace with your own fernet key
  sql_alchemy_conn: <base64 encoded connection string> # replace with your own connection string
 

