
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-configmap
data:
  airflow.cfg: |-
    [core]
    executor = KubernetesExecutor
    dags_folder = /opt/airflow/dags
    base_log_folder = /opt/airflow/logs
    logging_level = DEBUG
    hostname_callable = socket:gethostname
    load_examples = False
    [logging]
    logging_level = INFO
    remote_logging = False
